[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "molnet"
version = "0.0.0"
dependencies = [
    "matplotlib",
    "numpy",
    "absl-py",
    "tqdm",
    "ase",
    "scipy",
    "scikit-image",
    "torch",
    "torchvision",
    "torchaudio",
    "torchsummary",
    "torchmetrics",
    "tensorboard",
    "pyyaml",
    "ml-collections",
    "webdataset",
    "escnn",
]

[tool.setuptools.packages]
find = {}
